let menu = [
    {id:"1", name: "Caesar", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Salads", price: 8.99, quantity: 0},
    {id:"2", name: "Borsch", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Soups", price: 12.49, quantity: 0},
    {id:"3", name: "Name2", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Desserts", price: 3.72, quantity: 0},
    {id:"4", name: "Name3", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Snacks", price: 18.99, quantity: 0},
    {id:"5", name: "Name4", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Drinks", price: 18.99, quantity: 0},
    {id:"6", name: "Caesar2", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Salads", price: 18.99, quantity: 0},
    {id:"7", name: "Borsch2", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Soups", price: 8.92, quantity: 0},
    {id:"8", name: "Name7", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Desserts", price: 18.99, quantity: 0},
    {id:"9", name: "Name8", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Snacks", price: 18.99, quantity: 0},
    {id:"10", name: "Caesar3", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Salads", price: 8.99, quantity: 0},
    {id:"11", name: "Borsch3", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Soups", price: 3.72, quantity: 0},
    {id:"12", name: "Name2", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Desserts", price: 18.99, quantity: 0},
    {id:"13", name: "Name3", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Snacks", price: 1.69, quantity: 0},
    {id:"14", name: "Vodka", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Drinks", price: 18.99, quantity: 0},
    {id:"15", name: "Caesar4", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Salads", price: 18.99, quantity: 0},
    {id:"16", name: "Borsch4", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Soups", price: 3.72, quantity: 0},
    {id:"17", name: "Name7", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Desserts", price: 18.99, quantity: 0},
    {id:"18", name: "Name8", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Snacks", price: 18.99, quantity: 0},
    {id:"19", name: "Salianka", pic:"pictures/avocado_blackbean_eggs.jpg", category: "Soups", price: 3.72, quantity: 0},
]
